// File generated by FlutterFire CLI.
// Run: dart pub global activate flutterfire_cli
//      flutterfire configure
//
// Replace placeholder values below with your Firebase project config,
// or regenerate this file with `flutterfire configure`.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Project: fluter-app-28af9 (Cloud Firestore — not Realtime Database)
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT7b8SrjbmZoi84_WOBRma34h28Dn-jMA',
    appId: '1:91091871330:web:68ae519e1260a6e5dbd33b',
    messagingSenderId: '91091871330',
    projectId: 'fluter-app-28af9',
    authDomain: 'fluter-app-28af9.firebaseapp.com',
    storageBucket: 'fluter-app-28af9.firebasestorage.app',
    measurementId: 'G-3ZBN7GS8T1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY',
    appId: 'YOUR_ANDROID_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'fluter-app-28af9',
    storageBucket: 'fluter-app-28af9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'fluter-app-28af9',
    storageBucket: 'fluter-app-28af9.firebasestorage.app',
    iosBundleId: 'com.example.productManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'fluter-app-28af9',
    storageBucket: 'fluter-app-28af9.firebasestorage.app',
    iosBundleId: 'com.example.productManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_WINDOWS_API_KEY',
    appId: 'YOUR_WINDOWS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'fluter-app-28af9',
    storageBucket: 'fluter-app-28af9.firebasestorage.app',
  );
}
